---
layout: page
title: 빅데이터 
subtitle: "기계학습 예측모형"
author:
    name: xwMOOC
    url: https://www.facebook.com/groups/tidyverse/
    affiliation: Tidyverse Korea
date: "`r Sys.Date()`"
output:
  html_document: 
    toc: yes
    toc_float: true
    highlight: tango
    code_folding: show
    number_section: true
    self_contained: true
editor_options: 
  chunk_output_type: console
---


``` {r, include=FALSE}
# source("tools/chunk-options.R")
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE,
                    comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')
```

# RDD 자료변환 개요 {#pyspark-rdd-transformation-overview}

```{r setup-python}
library(reticulate)
use_condaenv("anaconda3")
```


```{python hello-spark}
import findspark
findspark.init()
import pyspark

# sc = pyspark.SparkContext(appName="SparkContext")
sc = pyspark.SparkContext()

# SparkContext 버전
print("스파크 컨텍스트 버젼: ", sc.version)

# SparkContext 파이썬 버전
print("Spark Context 파이썬 버전:", sc.pythonVer)

# SparkContext 마스터
print("Spark Context 마스터:", sc.master)
```





